
# Site settings
title: Kachi O's webpage
email: 
description: "Personal website"
baseurl: ""
url: "http://kachio.github.io"
github_username:  kachio

# Build settings
markdown: kramdown
permalink: pretty
permalink: /blog/:year/:month/:day/:title

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
# Google services
google_analytics: UA-88963947-1
  

