
# Site settings
title: Kachi O's webpage
email: 
description: "Personal website"
baseurl: ""
url: "http://kachio.github.io"
github_username:  kachio

# Build settings
markdown: kramdown
#permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
permalink: /blog/:year/:month/:day/:title
