
# Site settings
title: 
email: 
description:
baseurl: ""
url: "http://kachio.github.io"
github_username:  kachio
twitter_username: kachiodemz

# Build settings
markdown: kramdown
permalink: pretty
#permalink: /blog/:year/:month/:day/:title
permalink: /blog/:title

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
# Google services
google_analytics: UA-88963947-1
  

